export type BlogPost = {
  id: number;
  slug: string;
  title: string;
  excerpt: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  category: string;
  tags: string[];
  imageUrl: string;
};

// Sample blog posts data
export const leakDetectionPosts: BlogPost[] = [
  {
    id: 1,
    slug: "acoustic-leak-detection-find-hidden-leaks",
    title: "Acoustic Leak Detection: Find Hidden Water Leaks",
    excerpt: "Learn how acoustic leak detection uses sound to find hidden leaks at home. Get simple tips, tool guide, safety advice, and when to call a pro.",
    author: "Discount Leak Detection Team",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Plumbing",
    tags: ["acoustic leak detection", "water leak detection", "DIY plumbing", "leak detection tools", "home maintenance", "pipe leaks"],
    imageUrl: "/images/acoustic-leak-detection-find-hidden-leaks.webp"
  },
  {
    id: 2,
    slug: "automatic-leak-detection-systems",
    title: "Automatic leak detection: How to spot and stop home leaks",
    excerpt: "Automatic leak detection: A simple guide to choosing, placing, and testing sensors that find and stop water leaks before they cause damage.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water leak sensors", "home safety", "flow meters", "moisture sensors", "sound sensors", "leak prevention"],
    imageUrl: "/images/automatic-leak-detection-systems.webp"
  },
  {
    id: 3,
    slug: "automotive-leak-detection-guide",
    title: "Automotive leak detection: Find and fix car leaks",
    excerpt: "Easy guide for Automotive leak detection. Spot fluid drips, try simple tools, and learn steps to find and fix small leaks at home.",
    author: "Discount Leak Detection",
    authorRole: "Automotive Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Automotive",
    tags: ["automotive leak detection", "car maintenance", "fluid leaks", "DIY auto repair", "leak detection tools", "oil leak", "coolant leak"],
    imageUrl: "/images/automotive-leak-detection-guide.webp"
  },
  {
    id: 4,
    slug: "basement-leak-detection-steps",
    title: "Basement leak detection: find hidden water and prevent damage",
    excerpt: "Basement leak detection tips help you find water, stop damage, and keep your home dry. Learn what to look for, tools to use, and basic fixes.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Home Maintenance",
    tags: ["basement leak", "leak detection", "DIY leaks", "moisture meter", "water stains", "basement waterproofing", "mold prevention"],
    imageUrl: "/images/basement-leak-detection-steps.webp"
  },
  {
    id: 5,
    slug: "bathroom-leak-detection-guide",
    title: "Bathroom leak detection: Simple steps to find and fix drips",
    excerpt: "Learn easy steps for Bathroom leak detection. Find hidden drips, test pipes, check tiles, and stop water damage before it gets worse.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Leak Detection",
    tags: ["bathroom leak detection", "find bathroom leaks", "DIY plumbing", "water damage prevention", "leak detection tools", "hidden leaks", "save water"],
    imageUrl: "/images/bathroom-leak-detection-guide.webp"
  },
  {
    id: 6,
    slug: "best-leak-detection-method",
    title: "Best leak detection method to find water leaks fast",
    excerpt: "Learn easy ways and tools for the Best leak detection method. Find hidden water leaks fast, protect walls and floors, and know when to call for help.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water leaks", "home repair", "DIY plumbing", "infrared leak detection", "acoustic leak detection", "pressure test"],
    imageUrl: "/images/best-leak-detection-method.webp"
  },
  {
    id: 7,
    slug: "bubble-solution-for-leak-detection-guide",
    title: "Bubble solution for leak detection: DIY mix and use",
    excerpt: "Learn how to mix and use bubble solution for leak detection at home. Step by step tips to find and fix leaks, stay safe, and save money.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Leak Detection",
    tags: ["leak detection", "bubble solution", "DIY leak test", "pipe leak test", "gas leak detection", "home maintenance", "air leak detection"],
    imageUrl: "/images/bubble-solution-for-leak-detection-guide.webp"
  },
  {
    id: 8,
    slug: "cctv-water-pipe-leak-detection-guide",
    title: "CCTV water pipe leak detection: How it works & tips",
    excerpt: "Learn how CCTV water pipe leak detection works, with clear steps, safety checks, and answers to common questions on finding hidden leaks.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Home Maintenance",
    tags: ["CCTV leak detection", "pipe inspection", "water leaks", "DIY plumbing", "home repair", "pipe camera", "prevent water damage"],
    imageUrl: "/images/cctv-water-pipe-leak-detection-guide.webp"
  },
  {
    id: 9,
    slug: "ceiling-leak-detection-methods",
    title: "Ceiling leak detection: Easy ways to find and fix leaks",
    excerpt: "Learn easy steps to spot and track water leaks in your ceiling. Find simple tools and safety tips for Ceiling leak detection at home.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["ceiling leak", "leak detection", "home repair", "moisture meter", "diy plumbing", "roof leak detection", "water stains"],
    imageUrl: "/images/ceiling-leak-detection-methods.webp"
  },
  {
    id: 10,
    slug: "most-common-household-water-leaks",
    title: "Common water leaks: How to spot, find and fix them",
    excerpt: "Learn how to spot and fix common water leaks around your home. Easy steps to find hidden drips, test pipes and stop leaks before damage starts.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Plumbing",
    tags: ["water leaks", "leak detection", "home maintenance", "plumbing tips", "DIY repair", "water conservation", "prevent leaks"],
    imageUrl: "/images/most-common-household-water-leaks.webp"
  },
  {
    id: 11,
    slug: "crawl-space-leak-detection-find-fix-leaks",
    title: "Crawl space leak detection: Find and fix leaks",
    excerpt: "Learn simple ways for crawl space leak detection. See how to spot water, use easy tools, and know when to get help to keep your home dry.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Leak Detection",
    tags: ["crawl space", "leak detection", "home maintenance", "water damage", "DIY", "moisture meter", "foundation leaks"],
    imageUrl: "/images/crawl-space-leak-detection-find-fix-leaks.webp"
  },
  {
    id: 12,
    slug: "diy-leak-detection-home-leaks",
    title: "DIY leak detection: Find hidden home leaks fast",
    excerpt: "Learn how to find hidden home leaks with DIY leak detection. Get easy steps, simple tools, safety tips and advice on when to call for help.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["DIY leak detection", "Leak detection", "Home leaks", "Water leaks", "Gas leaks", "Home repair"],
    imageUrl: "/images/diy-leak-detection-home-leaks.webp"
  },
  {
    id: 13,
    slug: "dye-testing-leak-detection-methods",
    title: "Dye testing leak detection: A simple home guide",
    excerpt: "Learn simple steps for dye testing leak detection at home. See tools to use, safety tips, cost guides, and when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["dye testing", "leak detection", "DIY leak test", "plumbing leaks", "pool leak", "pipe leak"],
    imageUrl: "/images/dye-testing-leak-detection-methods.webp"
  },
  {
    id: 14,
    slug: "early-leak-detection-find-fix-leaks",
    title: "Early leak detection: How to find and fix leaks fast",
    excerpt: "Early leak detection helps you spot small water leaks before they become big damage. Learn simple tests, signs, tools, and DIY fixes to protect your home.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water leaks", "home repair", "DIY leak test", "water meter", "mold prevention", "plumbing tips"],
    imageUrl: "/images/early-leak-detection-find-fix-leaks.webp"
  },
  {
    id: 15,
    slug: "electronic-leak-detection-methods",
    title: "Electronic leak detection: tips to find hidden leaks",
    excerpt: "Learn basic steps, tools, and tips for electronic leak detection at home. Find hidden pipe or floor leaks safely and save water and money.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Plumbing",
    tags: ["electronic leak detection", "leak detection tools", "home plumbing", "moisture meter", "ground microphone", "tracer gas", "save water"],
    imageUrl: "/images/electronic-leak-detection-methods.webp"
  },
  {
    id: 16,
    slug: "fiber-optic-leak-detection-home-guide",
    title: "Fiber optic leak detection guide: Home setup and tips",
    excerpt: "Learn how fiber optic leak detection works at home, from setup to care. Spot hidden water leaks early, avoid big repair costs and keep pipes safe.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["fiber optic", "leak detection", "home safety", "water leaks", "plumbing maintenance", "DIY installation"],
    imageUrl: "/images/fiber-optic-leak-detection-home-guide.webp"
  },
  {
    id: 17,
    slug: "fire-sprinkler-leak-detection-find-fix-leaks",
    title: "Fire sprinkler leak detection: How to find and fix leaks",
    excerpt: "Learn easy Fire sprinkler leak detection tips to spot, test, and fix leaks at home. Get clear steps, tools to use, and cost info.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Leak Detection",
    tags: ["fire safety", "sprinkler leak", "plumbing", "water damage", "leak detection", "DIY", "home safety"],
    imageUrl: "/images/fire-sprinkler-leak-detection-find-fix-leaks.webp"
  },
  {
    id: 18,
    slug: "fluorescent-dye-leak-detection-guide",
    title: "Fluorescent Dye Leak Detection Guide for Home Leaks",
    excerpt: "Learn how fluorescent dye leak detection works, what tools you need, and simple steps to spot and fix leaks safely in your home.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["fluorescent dye leak detection", "UV leak detection", "home plumbing", "DIY leak repair", "HVAC maintenance", "pipe leak detection", "leak detection tools"],
    imageUrl: "/images/fluorescent-dye-leak-detection-guide.webp"
  },
  {
    id: 19,
    slug: "foundation-leak-detection-guide",
    title: "Foundation leak detection: How to find and fix leaks",
    excerpt: "Find foundation leaks fast with simple steps. Learn warning signs, easy checks, basic fixes, and when to seek help. Foundation leak detection tips.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["foundation leak detection", "home leaks", "slab leak", "leak prevention", "foundation repair", "DIY plumbing", "water meter test"],
    imageUrl: "images/foundation-leak-detection-guide.webp"
  },
  {
    id: 20,
    slug: "gas-leak-detection-safety-guide",
    title: "Gas leak detection: simple steps to find leaks",
    excerpt: "Learn how gas leak detection works, easy steps to spot leaks, tools to use, safety tips, and when to get help for a safer home.",
    author: "Discount Leak Detection",
    authorRole: "Home Safety Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Safety",
    tags: ["gas leak detection", "home safety", "DIY gas leak test", "gas safety", "leak detection tools", "natural gas leaks", "propane safety"],
    imageUrl: "/images/gas-leak-detection-safety-guide.webp"
  },
  {
    id: 21,
    slug: "helium-leak-detection-find-fix-leaks",
    title: "Helium leak detection: How to find and fix leaks",
    excerpt: "Learn what Helium leak detection is, how it works, the tools and safety tips you need, and simple steps to find and fix leaks at home.",
    author: "Discount Leak Detection Team",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["helium leak detection", "tracer gas", "leak detection tools", "vacuum testing", "sniffer probe", "safety tips", "home maintenance"],
    imageUrl: "/images/helium-leak-detection-find-fix-leaks.webp"
  },
  {
    id: 22,
    slug: "how-to-find-hidden-water-leaks",
    title: "How to Find Hidden Water Leaks at Home",
    excerpt: "Learn simple steps to find hidden water leaks at home. You’ll learn where to look, easy tests to try, and when to get extra help.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "5 Min.",
    category: "Plumbing",
    tags: ["hidden water leaks", "water leak detection", "DIY plumbing", "water meter test", "home maintenance", "leak prevention", "slab leaks"],
    imageUrl: "/images/how-to-find-hidden-water-leaks.webp"
  },
  {
    id: 23,
    slug: "how-does-leak-detection-work",
    title: "How does leak detection work: Simple home guide",
    excerpt: "Learn how does leak detection work with easy tests and simple sensors. Spot leaks early and protect your home with safe steps.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water leaks", "plumbing", "home safety", "DIY leak detection", "water damage", "mold prevention"],
    imageUrl: "/images/how-does-leak-detection-work.webp"
  },
  {
    id: 24,
    slug: "how-to-detect-leaks-in-your-home",
    title: "How to detect leaks: Easy steps to find drips",
    excerpt: "How to detect leaks in your home with easy steps, spot hidden drips indoors or outdoors, and use simple tips to save water and avoid damage.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water meter", "DIY", "home repair", "water leaks", "indoor leaks", "outdoor leaks"],
    imageUrl: "/images/how-to-detect-leaks-in-your-home.webp"
  },
  {
    id: 25,
    slug: "hvac-leak-detection-guide",
    title: "HVAC leak detection: A simple guide for home fixes",
    excerpt: "Easy tips to find and fix leaks in your heating and cooling system. Get clear steps for HVAC leak detection at home and when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "HVAC Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "HVAC",
    tags: ["HVAC", "leak detection", "DIY HVAC", "home maintenance", "energy saving", "refrigerant leaks", "duct leaks"],
    imageUrl: "/images/hvac-leak-detection-guide.webp"
  },
  {
    id: 26,
    slug: "hydrostatic-leak-testing-guide",
    title: "Hydrostatic leak testing: A clear how-to guide",
    excerpt: "Learn how hydrostatic leak testing finds hidden leaks using water pressure. Get step-by-step tips, safety advice, cost info, and when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Plumbing",
    tags: ["hydrostatic leak testing", "leak detection", "plumbing guide", "pipe testing", "home maintenance", "hydrostatic test", "water leak"],
    imageUrl: "/images/hydrostatic-leak-testing-guide.webp"
  },
  {
    id: 27,
    slug: "infrared-camera-gas-leak-detection",
    title: "Infrared camera gas leak detection: How it works at home",
    excerpt: "Learn how infrared camera gas leak detection works at home, what gear you need, safety tips, and easy steps to spot leaks.",
    author: "Discount Leak Detection",
    authorRole: "Gas Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Gas Leak Detection",
    tags: ["infrared camera", "gas leak detection", "home safety", "DIY gas check", "leak detection tools", "rent infrared camera"],
    imageUrl: "/images/infrared-camera-gas-leak-detection.webp"
  },
  {
    id: 28,
    slug: "infrared-leak-detection-guide",
    title: "Infrared leak detection: How to find hidden home leaks",
    excerpt: "Learn how Infrared leak detection works, when to use it, simple DIY steps, safety checks, and when to hire a pro for hidden home leaks.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Maintenance",
    tags: ["infrared leak detection", "thermal imaging", "DIY leak detection", "home maintenance", "moisture detection", "water leaks"],
    imageUrl: "/images/infrared-leak-detection-guide.webp"
  },
  {
    id: 29,
    slug: "irrigation-leak-detection-guide",
    title: "Irrigation leak detection: Easy steps to find leaks",
    excerpt: "Irrigation leak detection: Learn easy steps to spot wet spots, use simple tools, and find leaks fast to save water and money.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Maintenance",
    tags: ["irrigation", "leak detection", "sprinkler system", "DIY", "yard maintenance", "water conservation", "irrigation repair"],
    imageUrl: "/images/irrigation-leak-detection-guide.webp"
  },
  {
    id: 30,
    slug: "kitchen-leak-detection-guide",
    title: "Kitchen leak detection: find and fix leaks quickly",
    excerpt: "Kitchen leak detection: Learn to spot hidden drips, use simple tools, make safe repairs, and know when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Home Maintenance",
    tags: ["kitchen leak detection", "DIY plumbing", "water leak", "leak detection tools", "prevent water damage", "home maintenance", "sink leaks"],
    imageUrl: "/images/kitchen-leak-detection-guide.webp"
  },
  {
    id: 31,
    slug: "complete-guide-to-leak-detection-methods",
    title: "Leak detection methods: Easy ways to find hidden leaks",
    excerpt: "Learn leak detection methods for home. Find hidden water or gas leaks with simple tests, easy tools, and clear steps to save money and avoid damage.",
    author: "Discount Leak Detection",
    authorRole: "DIY Home Repair Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "DIY Home Repair",
    tags: ["leak detection", "DIY", "water leaks", "gas leaks", "home maintenance", "plumbing tips"],
    imageUrl: "/images/complete-guide-to-leak-detection-methods.webp"
  },
  {
    id: 32,
    slug: "leak-detection-process",
    title: "Leak detection process - easy steps to find leaks at home",
    excerpt: "Learn how to spot, test, and find leaks at home. Follow easy steps in the leak detection process to save water and avoid damage.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["leak detection", "water leaks", "home plumbing", "DIY repair", "water saving", "leak prevention", "plumbing tools"],
    imageUrl: "/images/leak-detection-process.webp"
  },
  {
    id: 33,
    slug: "leak-detection-techniques",
    title: "Leak detection techniques you can try at home",
    excerpt: "Learn leak detection techniques to spot leaks early, try simple tests at home, and see what tools pros use.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["home leaks", "water leaks", "leak detection", "DIY leak tests", "water meter test", "thermal imaging", "acoustic leak detection"],
    imageUrl: "/images/leak-detection-techniques.webp"
  },
  {
    id: 34,
    slug: "latest-leak-detection-technology",
    title: "Leak detection technology: Easy Home Tests and Tips",
    excerpt: "Learn simple ways leak detection technology can spot hidden leaks at home. Easy steps, tips, and tools to keep your pipes safe and dry.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Improvement Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Improvement",
    tags: ["leak detection", "leak detection technology", "water leaks", "DIY leak test", "moisture meter", "thermal imaging", "pressure test"],
    imageUrl: "/images/latest-leak-detection-technology.webp"
  },
  {
    id: 35,
    slug: "leak-detection-training-guide",
    title: "Leak detection training: Easy steps to find leaks",
    excerpt: "Learn leak detection training with simple steps. Find out what tools you need, how to spot leaks, safety tips, and when to call for help.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Home Maintenance",
    tags: ["leak detection training", "DIY leak detection", "water leaks", "home plumbing", "leak detection tools", "hidden leaks", "safety tips"],
    imageUrl: "/images/leak-detection-training-guide.webp"
  },
  {
    id: 36,
    slug: "leak-monitoring-system-home-guide",
    title: "Leak monitoring system: A Simple Home Guide",
    excerpt: "Learn what a Leak monitoring system is, how to pick one, where to place sensors, and steps to keep it running to catch leaks early.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["leak monitoring system", "water leak detector", "home leak detection", "leak sensor placement", "DIY leak detection", "water leak alarm", "basement leak sensor"],
    imageUrl: "/images/leak-monitoring-system-home-guide.webp"
  },
  {
    id: 37,
    slug: "home-leak-prevention-guide",
    title: "Leak prevention tips: Easy ways to avoid water leaks",
    excerpt: "Learn leak prevention tips to spot drips, care for pipes, and fix small leaks fast. Avoid water damage with easy checks and simple steps.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["leak prevention", "water leaks", "home plumbing", "leak detection", "DIY plumbing", "pipe insulation", "water meter"],
    imageUrl: "/images/home-leak-prevention-guide.webp"
  },
  {
    id: 38,
    slug: "lidar-leak-detection-guide",
    title: "Easy Guide to Lidar Leak Detection",
    excerpt: "Learn Lidar leak detection basics, tool list, step by step checks, safety tips, cost ideas, and answers to common questions.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "5 Min.",
    category: "Leak Detection",
    tags: ["lidar leak detection", "leak detection methods", "home maintenance", "plumbing tips", "hidden leaks", "safety tips", "cost guide"],
    imageUrl: "/images/lidar-leak-detection-guide.webp"
  },
  {
    id: 39,
    slug: "marine-leak-detection-guide",
    title: "Marine leak detection: How to find and fix boat leaks",
    excerpt: "Learn simple steps to find, fix, and prevent boat leaks. This Marine leak detection guide covers tools, warning signs, safety tips, and when to call for help.",
    author: "Discount Leak Detection",
    authorRole: "Marine Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Marine Maintenance",
    tags: ["marine leak detection", "boat leaks", "hull leak", "boat maintenance", "leak detection tools", "bilge pump leaks", "pressure tester"],
    imageUrl: "/images/marine-leak-detection-guide.webp"
  },
  {
    id: 40,
    slug: "methane-leak-detection-guide",
    title: "Methane leak detection: A simple home guide",
    excerpt: "Learn simple steps and tools for Methane leak detection at home, how to spot leaks, stay safe, and know when to get help.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Safety Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Home Safety",
    tags: ["methane leak detection", "gas safety", "home maintenance", "DIY gas leak test", "handheld gas detector", "soap bubble test", "infrared gas detection"],
    imageUrl: "/images/methane-leak-detection-guide.webp"
  },
  {
    id: 41,
    slug: "oil-gas-leak-detection-home-guide",
    title: "Oil and Gas Leak Detection Home Guide",
    excerpt: "Easy guide to oil and gas leak detection at home. Spot signs, do simple checks, choose tools, prevent spills, and know when to get help.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["oil leak detection", "gas leak detection", "home safety", "DIY leak test", "soapy water leak test", "gas detector", "plumbing maintenance"],
    imageUrl: "/images/oil-gas-leak-detection-home-guide.webp"
  },
  {
    id: 42,
    slug: "pharmaceutical-leak-detection-guide",
    title: "Pharmaceutical leak detection: Easy steps to find leaks",
    excerpt: "Learn simple ways to spot, test and prevent leaks in drug containers. A clear guide to Pharmaceutical leak detection for safe, correct results.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["pharmaceutical leak detection", "leak testing", "bubble test", "pressure test", "vacuum test", "container sealing"],
    imageUrl: "/images/pharmaceutical-leak-detection-guide.webp"
  },
  {
    id: 43,
    slug: "pinhole-leak-detection-spot-tiny-leaks",
    title: "Pinhole Leak Detection: How to Spot Tiny Pipe Leaks",
    excerpt: "Learn simple Pinhole leak detection tips for home pipes: find, test, and fix tiny leaks before they cause water damage.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Plumbing",
    tags: ["pinhole leak", "leak detection", "water leak", "DIY plumbing", "home plumbing", "water damage prevention", "plumber tips"],
    imageUrl: "/images/pinhole-leak-detection-spot-tiny-leaks.webp"
  },
  {
    id: 44,
    slug: "pipe-leak-detection-guide",
    title: "Pipe leak detection: Find and fix small leaks",
    excerpt: "Learn clear steps to find, test, and stop small water leaks. Pipe leak detection tips cover signs, home checks, safety pointers, and when to get help.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Home Maintenance",
    tags: ["pipe leak detection", "DIY leak detection", "water meter reading", "toilet dye test", "moisture meter", "prevent pipe leaks"],
    imageUrl: "/images/pipe-leak-detection-guide.webp"
  },
  {
    id: 45,
    slug: "pipeline-leak-detection-guide",
    title: "Pipeline leak detection: Simple steps to find and fix leaks",
    excerpt: "Pipeline leak detection: Learn easy steps to spot, test, and prevent hidden pipeline leaks. Find tips on tools, tests, and when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "10 Min.",
    category: "Leak Detection",
    tags: ["pipeline leak detection", "leak detection", "water leak", "gas leak", "DIY leak test", "leak prevention", "home maintenance"],
    imageUrl: "/images/pipeline-leak-detection-guide.webp"
  },
  {
    id: 46,
    slug: "plumbing-leak-detection-home-guide",
    title: "Plumbing leak detection: How to find hidden leaks",
    excerpt: "Learn simple steps for Plumbing leak detection. Spot leaks, use easy home tools, check warning signs, and know when to call a plumber.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "10 Min.",
    category: "Plumbing",
    tags: ["leak detection", "plumbing", "DIY", "water leaks", "home maintenance", "infrared leak detection", "moisture meter"],
    imageUrl: "images/plumbing-leak-detection-home-guide.webp"
  },
  {
    id: 47,
    slug: "pool-leak-detection-spot-test-leaks",
    title: "Pool leak detection: how to spot and test leaks",
    excerpt: "Learn Pool leak detection at home. Spot leaks early with bucket, dye, pump tests, check fittings, and know when to call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Pool Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Pool Maintenance",
    tags: ["pool leak detection", "pool maintenance", "bucket test", "dye test", "pump test", "DIY pool leak", "skimmer leak", "pipe leak"],
    imageUrl: "/images/pool-leak-detection-spot-test-leaks.webp"
  },
  {
    id: 48,
    slug: "refrigerant-leak-detection-guide",
    title: "Refrigerant leak detection: Spot and fix home AC leaks",
    excerpt: "Learn simple steps for Refrigerant leak detection at home. Spot leaks early, pick the right tools, follow safety tips, and know when to call a pro.",
    author: "Discount Leak Detection Team",
    authorRole: "HVAC Maintenance Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "HVAC Maintenance",
    tags: ["refrigerant leak detection", "AC leak detection", "DIY AC repair", "HVAC maintenance", "leak detection tools", "safety tips", "energy efficiency"],
    imageUrl: "/images/refrigerant-leak-detection-guide.webp"
  },
  {
    id: 49,
    slug: "roof-leak-detection-easy-guide",
    title: "Roof leak detection: Easy steps to find and fix leaks",
    excerpt: "Learn simple Roof leak detection steps. Find early signs, use easy tools, stay safe on ladders, and know when to fix leaks yourself or call a pro.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Home Maintenance",
    tags: ["roof leak", "roof inspection", "moisture meter", "infrared camera", "DIY roof repair", "attic inspection", "leak detection"],
    imageUrl: "/images/roof-leak-detection-easy-guide.webp"
  },
  {
    id: 50,
    slug: "sewer-line-leak-detection-methods",
    title: "Sewer leak detection: easy ways to find hidden leaks",
    excerpt: "Learn sewer leak detection tips: spot warning signs, use simple tools, stay safe, and stop small issues before they grow.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["sewer leak", "leak detection", "DIY leak detection", "water leak", "home plumbing", "prevent leaks", "early signs"],
    imageUrl: "/images/sewer-line-leak-detection-methods.webp"
  },
  {
    id: 51,
    slug: "common-signs-of-a-water-leak",
    title: "Signs of water leak: How to spot and stop leaks fast",
    excerpt: "Learn the key Signs of water leak in your home. Find easy tips to spot leaks on walls, floors, and bills, and take simple steps to fix or prevent damage.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Maintenance",
    tags: ["water leak", "leak detection", "home repair", "DIY plumbing", "water damage", "leak prevention", "home maintenance"],
    imageUrl: "/images/common-signs-of-a-water-leak.webp"
  },
  {
    id: 52,
    slug: "slab-leak-detection-find-test-leaks",
    title: "Slab leak detection: How to find and test hidden leaks",
    excerpt: "Find hidden water leaks under your home slab with easy checks, warning signs, and tools. Learn slab leak detection steps and next actions.",
    author: "Discount Leak Detection",
    authorRole: "Plumbing Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Plumbing",
    tags: ["slab leak detection", "water leaks", "home plumbing", "DIY leak detection", "leak warning signs", "acoustic leak detection", "thermal leak detection"],
    imageUrl: "/images/slab-leak-detection-find-test-leaks.webp"
  },
  {
    id: 53,
    slug: "smart-home-leak-detection-guide",
    title: "Smart home leak detection: guide to find and fix leaks",
    excerpt: "Learn simple steps for Smart home leak detection. See how sensors work, where to put them, and what to do when they alert you.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Maintenance",
    tags: ["smart home", "leak detection", "water sensors", "home safety", "DIY plumbing", "water leak prevention"],
    imageUrl: "/images/smart-home-leak-detection-guide.webp"
  },
  {
    id: 54,
    slug: "smart-leak-detection-spot-stop-hidden-leaks",
    title: "Smart leak detection: How to spot and stop hidden leaks",
    excerpt: "Learn what Smart leak detection is and how to spot hidden water leaks, pick the right sensors, set alerts, and act fast to protect your home.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Home Maintenance",
    tags: ["smart leak detection", "water leak sensors", "leak detection", "home water leaks", "prevent water damage", "leak detectors", "early leak alert"],
    imageUrl: "/images/smart-leak-detection-spot-stop-hidden-leaks.webp"
  },
  {
    id: 55,
    slug: "smoke-test-leak-detection-guide",
    title: "Smoke test leak detection: Home guide to find pipe leaks",
    excerpt: "Learn simple steps for Smoke test leak detection to find hidden pipe leaks at home safely. Get tips on tools, safety steps, and when to call for help.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "9 Min.",
    category: "Leak Detection",
    tags: ["smoke test", "leak detection", "pipe leaks", "DIY plumbing", "home maintenance", "plumbing tips", "leak detection tools"],
    imageUrl: "/images/smoke-test-leak-detection-guide.webp"
  },
  {
    id: 56,
    slug: "sprinkler-leak-detection-guide",
    title: "Sprinkler leak detection: How to spot leaks fast",
    excerpt: "Learn simple Sprinkler leak detection steps. Spot early signs, try easy tests, use basic tools, and know when to call a pro. Prevent water waste.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Improvement Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Home Improvement",
    tags: ["sprinkler leak detection", "DIY leak test", "lawn care", "irrigation tools", "leak detection", "water conservation", "sprinkler maintenance"],
    imageUrl: "/images/sprinkler-leak-detection-guide.webp"
  },
  {
    id: 57,
    slug: "thermal-imaging-leak-detection-guide",
    title: "Thermal imaging leak detection: A simple home guide",
    excerpt: "Thermal imaging leak detection: learn simple steps to spot hidden water leaks, tools to use, safety tips and when to call for professional help.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Leak Detection",
    tags: ["thermal imaging", "leak detection", "home maintenance", "DIY leak repair", "infrared camera", "moisture meter", "water leaks"],
    imageUrl: "/images/thermal-imaging-leak-detection-guide.webp"
  },
  {
    id: 58,
    slug: "tracer-gas-leak-detection-methods",
    title: "Tracer gas leak detection: Easy steps to find pipe leaks",
    excerpt: "Tracer gas leak detection in easy steps. Find out what tools, gas mix, and safety tips you need to spot pipe leaks yourself and avoid false alarms.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["tracer gas", "leak detection", "pipe leak", "helium leak detection", "hydrogen leak detection", "underground leak detection"],
    imageUrl: "/images/tracer-gas-leak-detection-methods.webp"
  },
  {
    id: 59,
    slug: "ultrasonic-flow-meter-leak-detection",
    title: "Ultrasonic flow meter leak detection: Easy pipe leak guide",
    excerpt: "Learn how ultrasonic flow meter leak detection works and find hidden water leaks in pipes. Step by step guide with safety and care tips.",
    author: "Discount Leak Detection Team",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["ultrasonic flow meter", "pipe leak detection", "acoustic leak detection", "home plumbing", "DIY leak detection", "water leak detection", "safety tips"],
    imageUrl: "/images/ultrasonic-flow-meter-leak-detection.webp"
  },
  {
    id: 60,
    slug: "ultrasonic-leak-detection-guide",
    title: "Ultrasonic leak detection: How to find hidden leaks",
    excerpt: "Learn how ultrasonic leak detection finds hidden leaks, what tools you need, step-by-step tips, safety advice, and ways to save on repair costs.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Leak Detection",
    tags: ["ultrasonic leak detection", "leak detection tools", "DIY plumbing", "prevent water damage", "safety tips", "energy savings", "home maintenance"],
    imageUrl: "/images/ultrasonic-leak-detection-guide.webp"
  },
  {
    id: 61,
    slug: "underground-leak-detection-find-leaks",
    title: "Underground leak detection: how to find hidden water leaks",
    excerpt: "Learn easy ways for Underground leak detection. Spot warning signs, use simple tools, check your meter, narrow the leak spot, and stay safe when digging.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "12 Min.",
    category: "Home Maintenance",
    tags: ["underground leak detection", "water leak detection", "DIY plumbing", "water meter test", "acoustic leak detection", "moisture meter", "thermal camera"],
    imageUrl: "/images/underground-leak-detection-find-leaks.webp"
  },
  {
    id: 62,
    slug: "wall-leak-detection-guide",
    title: "Wall leak detection guide: how to spot and fix hidden leaks",
    excerpt: "Learn how Wall leak detection works. Find warning signs, use simple tools, test your meter, and know when to get help.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Leak Detection",
    tags: ["wall leak detection", "hidden leaks", "moisture meter", "acoustic leak detection", "thermal imaging", "DIY leak detection"],
    imageUrl: "/images/wall-leak-detection-guide.webp"
  },
  {
    id: 63,
    slug: "water-leak-detection-home-guide",
    title: "Water leak detection: Simple steps and tools",
    excerpt: "Learn easy steps and simple tools for water leak detection at home. Spot drips, test pipes, and prevent damage with clear, handy tips.",
    author: "Discount Leak Detection",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "6 Min.",
    category: "Home Maintenance",
    tags: ["water leak detection", "home plumbing", "DIY leak detection", "leak prevention", "moisture meter", "dye test", "home repair"],
    imageUrl: "/images/water-leak-detection-home-guide.webp"
  },
  {
    id: 64,
    slug: "what-is-acoustic-leak-detection",
    title: "What is acoustic leak detection? A simple guide",
    excerpt: "Learn what acoustic leak detection is, why it matters, the tools you need, and simple steps to find hidden leaks at home.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["acoustic leak detection", "leak detection", "water leaks", "detect hidden leaks", "DIY leak detection", "plumbing"],
    imageUrl: "/images/what-is-acoustic-leak-detection.webp"
  },
  {
    id: 65,
    slug: "whole-house-leak-detection-system-guide",
    title: "Whole house leak detection system: Find and stop leaks",
    excerpt: "Learn how a whole house leak detection system works, spot hidden drips, install and test it, and keep your home safe from water damage.",
    author: "Discount Leak Detection",
    authorRole: "Leak Detection Expert",
    date: "2025-07-19",
    readTime: "7 Min.",
    category: "Leak Detection",
    tags: ["leak detection", "water leak", "home maintenance", "plumbing tips", "water damage prevention", "DIY installation"],
    imageUrl: "/images/whole-house-leak-detection-system-guide.webp"
  },
  {
    id: 66,
    slug: "wifi-water-leak-detection-setup-tips",
    title: "WiFi water leak detection: How to spot and stop home leaks",
    excerpt: "Learn how WiFi water leak detection works, how to choose, install, and test sensors, and when to call a plumber to protect your home.",
    author: "Discount Leak Detection Team",
    authorRole: "Home Maintenance Expert",
    date: "2025-07-19",
    readTime: "11 Min.",
    category: "Home Maintenance",
    tags: ["WiFi water leak detection", "water leak sensors", "home water leaks", "leak prevention", "DIY home maintenance", "smart home devices", "emergency plumbing"],
    imageUrl: "/images/wifi-water-leak-detection-setup-tips.webp"
  },
  {
    id: 67,
    slug: "wireless-leak-detection-home-guide",
    title: "Wireless leak detection: A simple home guide",
    excerpt: "Learn how wireless leak detection works, how to pick, install, and care for detectors to spot leaks early and protect your home.",
    author: "Discount Leak Detection",
    authorRole: "Home Improvement Expert",
    date: "2025-07-19",
    readTime: "8 Min.",
    category: "Home Improvement",
    tags: ["wireless leak detection", "water leak sensors", "home maintenance", "DIY plumbing", "leak detectors", "smart home", "water damage prevention"],
    imageUrl: "/images/wireless-leak-detection-home-guide.webp"
  }
];
